[build]
  functions = "netlify/functions"

[functions]
directory = "netlify/functions"

[dev]
  command = "npm run dev:vite"
  port = 8888
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200